// Code generated by gamwsdl/main.go. DO NOT EDIT.
package company

import (
	"errors"
)

func NewApiError(reason string) error {
	return &ApiError{
		Reason: reason,
	}
}

func (e *ApiError) Error() string {
	return "ApiError error: " + e.Reason
}

func (e *ApiError) Is(target error) bool {
	var errType *ApiError
	return errors.As(target, &errType)
}

func NewApiException(reason string) error {
	return &ApiException{
		Reason: reason,
	}
}

func (e *ApiException) Error() string {
	return "ApiException error: " + e.Reason
}

func (e *ApiException) Is(target error) bool {
	var errType *ApiException
	return errors.As(target, &errType)
}

func NewApiVersionError(reason string) error {
	return &ApiVersionError{
		Reason: reason,
	}
}

func (e *ApiVersionError) Error() string {
	return "ApiVersionError error: " + e.Reason
}

func (e *ApiVersionError) Is(target error) bool {
	var errType *ApiVersionError
	return errors.As(target, &errType)
}

func NewApplicationException(reason string) error {
	return &ApplicationException{
		Reason: reason,
	}
}

func (e *ApplicationException) Error() string {
	return "ApplicationException error: " + e.Reason
}

func (e *ApplicationException) Is(target error) bool {
	var errType *ApplicationException
	return errors.As(target, &errType)
}

func NewAuthenticationError(reason string) error {
	return &AuthenticationError{
		Reason: reason,
	}
}

func (e *AuthenticationError) Error() string {
	return "AuthenticationError error: " + e.Reason
}

func (e *AuthenticationError) Is(target error) bool {
	var errType *AuthenticationError
	return errors.As(target, &errType)
}

func NewCollectionSizeError(reason string) error {
	return &CollectionSizeError{
		Reason: reason,
	}
}

func (e *CollectionSizeError) Error() string {
	return "CollectionSizeError error: " + e.Reason
}

func (e *CollectionSizeError) Is(target error) bool {
	var errType *CollectionSizeError
	return errors.As(target, &errType)
}

func NewCommonError(reason string) error {
	return &CommonError{
		Reason: reason,
	}
}

func (e *CommonError) Error() string {
	return "CommonError error: " + e.Reason
}

func (e *CommonError) Is(target error) bool {
	var errType *CommonError
	return errors.As(target, &errType)
}

func NewCompanyCreditStatusError(reason string) error {
	return &CompanyCreditStatusError{
		Reason: reason,
	}
}

func (e *CompanyCreditStatusError) Error() string {
	return "CompanyCreditStatusError error: " + e.Reason
}

func (e *CompanyCreditStatusError) Is(target error) bool {
	var errType *CompanyCreditStatusError
	return errors.As(target, &errType)
}

func NewCompanyError(reason string) error {
	return &CompanyError{
		Reason: reason,
	}
}

func (e *CompanyError) Error() string {
	return "CompanyError error: " + e.Reason
}

func (e *CompanyError) Is(target error) bool {
	var errType *CompanyError
	return errors.As(target, &errType)
}

func NewCrossSellError(reason string) error {
	return &CrossSellError{
		Reason: reason,
	}
}

func (e *CrossSellError) Error() string {
	return "CrossSellError error: " + e.Reason
}

func (e *CrossSellError) Is(target error) bool {
	var errType *CrossSellError
	return errors.As(target, &errType)
}

func NewCustomFieldValueError(reason string) error {
	return &CustomFieldValueError{
		Reason: reason,
	}
}

func (e *CustomFieldValueError) Error() string {
	return "CustomFieldValueError error: " + e.Reason
}

func (e *CustomFieldValueError) Is(target error) bool {
	var errType *CustomFieldValueError
	return errors.As(target, &errType)
}

func NewExchangeSignupApiError(reason string) error {
	return &ExchangeSignupApiError{
		Reason: reason,
	}
}

func (e *ExchangeSignupApiError) Error() string {
	return "ExchangeSignupApiError error: " + e.Reason
}

func (e *ExchangeSignupApiError) Is(target error) bool {
	var errType *ExchangeSignupApiError
	return errors.As(target, &errType)
}

func NewFeatureError(reason string) error {
	return &FeatureError{
		Reason: reason,
	}
}

func (e *FeatureError) Error() string {
	return "FeatureError error: " + e.Reason
}

func (e *FeatureError) Is(target error) bool {
	var errType *FeatureError
	return errors.As(target, &errType)
}

func NewInternalApiError(reason string) error {
	return &InternalApiError{
		Reason: reason,
	}
}

func (e *InternalApiError) Error() string {
	return "InternalApiError error: " + e.Reason
}

func (e *InternalApiError) Is(target error) bool {
	var errType *InternalApiError
	return errors.As(target, &errType)
}

func NewInvalidEmailError(reason string) error {
	return &InvalidEmailError{
		Reason: reason,
	}
}

func (e *InvalidEmailError) Error() string {
	return "InvalidEmailError error: " + e.Reason
}

func (e *InvalidEmailError) Is(target error) bool {
	var errType *InvalidEmailError
	return errors.As(target, &errType)
}

func NewInvalidUrlError(reason string) error {
	return &InvalidUrlError{
		Reason: reason,
	}
}

func (e *InvalidUrlError) Error() string {
	return "InvalidUrlError error: " + e.Reason
}

func (e *InvalidUrlError) Is(target error) bool {
	var errType *InvalidUrlError
	return errors.As(target, &errType)
}

func NewInventoryClientApiError(reason string) error {
	return &InventoryClientApiError{
		Reason: reason,
	}
}

func (e *InventoryClientApiError) Error() string {
	return "InventoryClientApiError error: " + e.Reason
}

func (e *InventoryClientApiError) Is(target error) bool {
	var errType *InventoryClientApiError
	return errors.As(target, &errType)
}

func NewLabelEntityAssociationError(reason string) error {
	return &LabelEntityAssociationError{
		Reason: reason,
	}
}

func (e *LabelEntityAssociationError) Error() string {
	return "LabelEntityAssociationError error: " + e.Reason
}

func (e *LabelEntityAssociationError) Is(target error) bool {
	var errType *LabelEntityAssociationError
	return errors.As(target, &errType)
}

func NewMcmError(reason string) error {
	return &McmError{
		Reason: reason,
	}
}

func (e *McmError) Error() string {
	return "McmError error: " + e.Reason
}

func (e *McmError) Is(target error) bool {
	var errType *McmError
	return errors.As(target, &errType)
}

func NewNetworkError(reason string) error {
	return &NetworkError{
		Reason: reason,
	}
}

func (e *NetworkError) Error() string {
	return "NetworkError error: " + e.Reason
}

func (e *NetworkError) Is(target error) bool {
	var errType *NetworkError
	return errors.As(target, &errType)
}

func NewNotNullError(reason string) error {
	return &NotNullError{
		Reason: reason,
	}
}

func (e *NotNullError) Error() string {
	return "NotNullError error: " + e.Reason
}

func (e *NotNullError) Is(target error) bool {
	var errType *NotNullError
	return errors.As(target, &errType)
}

func NewNullError(reason string) error {
	return &NullError{
		Reason: reason,
	}
}

func (e *NullError) Error() string {
	return "NullError error: " + e.Reason
}

func (e *NullError) Is(target error) bool {
	var errType *NullError
	return errors.As(target, &errType)
}

func NewParseError(reason string) error {
	return &ParseError{
		Reason: reason,
	}
}

func (e *ParseError) Error() string {
	return "ParseError error: " + e.Reason
}

func (e *ParseError) Is(target error) bool {
	var errType *ParseError
	return errors.As(target, &errType)
}

func NewPermissionError(reason string) error {
	return &PermissionError{
		Reason: reason,
	}
}

func (e *PermissionError) Error() string {
	return "PermissionError error: " + e.Reason
}

func (e *PermissionError) Is(target error) bool {
	var errType *PermissionError
	return errors.As(target, &errType)
}

func NewPublisherQueryLanguageContextError(reason string) error {
	return &PublisherQueryLanguageContextError{
		Reason: reason,
	}
}

func (e *PublisherQueryLanguageContextError) Error() string {
	return "PublisherQueryLanguageContextError error: " + e.Reason
}

func (e *PublisherQueryLanguageContextError) Is(target error) bool {
	var errType *PublisherQueryLanguageContextError
	return errors.As(target, &errType)
}

func NewPublisherQueryLanguageSyntaxError(reason string) error {
	return &PublisherQueryLanguageSyntaxError{
		Reason: reason,
	}
}

func (e *PublisherQueryLanguageSyntaxError) Error() string {
	return "PublisherQueryLanguageSyntaxError error: " + e.Reason
}

func (e *PublisherQueryLanguageSyntaxError) Is(target error) bool {
	var errType *PublisherQueryLanguageSyntaxError
	return errors.As(target, &errType)
}

func NewQuotaError(reason string) error {
	return &QuotaError{
		Reason: reason,
	}
}

func (e *QuotaError) Error() string {
	return "QuotaError error: " + e.Reason
}

func (e *QuotaError) Is(target error) bool {
	var errType *QuotaError
	return errors.As(target, &errType)
}

func NewRegExError(reason string) error {
	return &RegExError{
		Reason: reason,
	}
}

func (e *RegExError) Error() string {
	return "RegExError error: " + e.Reason
}

func (e *RegExError) Is(target error) bool {
	var errType *RegExError
	return errors.As(target, &errType)
}

func NewRequiredCollectionError(reason string) error {
	return &RequiredCollectionError{
		Reason: reason,
	}
}

func (e *RequiredCollectionError) Error() string {
	return "RequiredCollectionError error: " + e.Reason
}

func (e *RequiredCollectionError) Is(target error) bool {
	var errType *RequiredCollectionError
	return errors.As(target, &errType)
}

func NewRequiredError(reason string) error {
	return &RequiredError{
		Reason: reason,
	}
}

func (e *RequiredError) Error() string {
	return "RequiredError error: " + e.Reason
}

func (e *RequiredError) Is(target error) bool {
	var errType *RequiredError
	return errors.As(target, &errType)
}

func NewRequiredNumberError(reason string) error {
	return &RequiredNumberError{
		Reason: reason,
	}
}

func (e *RequiredNumberError) Error() string {
	return "RequiredNumberError error: " + e.Reason
}

func (e *RequiredNumberError) Is(target error) bool {
	var errType *RequiredNumberError
	return errors.As(target, &errType)
}

func NewServerError(reason string) error {
	return &ServerError{
		Reason: reason,
	}
}

func (e *ServerError) Error() string {
	return "ServerError error: " + e.Reason
}

func (e *ServerError) Is(target error) bool {
	var errType *ServerError
	return errors.As(target, &errType)
}

func NewSiteError(reason string) error {
	return &SiteError{
		Reason: reason,
	}
}

func (e *SiteError) Error() string {
	return "SiteError error: " + e.Reason
}

func (e *SiteError) Is(target error) bool {
	var errType *SiteError
	return errors.As(target, &errType)
}

func NewStatementError(reason string) error {
	return &StatementError{
		Reason: reason,
	}
}

func (e *StatementError) Error() string {
	return "StatementError error: " + e.Reason
}

func (e *StatementError) Is(target error) bool {
	var errType *StatementError
	return errors.As(target, &errType)
}

func NewStringFormatError(reason string) error {
	return &StringFormatError{
		Reason: reason,
	}
}

func (e *StringFormatError) Error() string {
	return "StringFormatError error: " + e.Reason
}

func (e *StringFormatError) Is(target error) bool {
	var errType *StringFormatError
	return errors.As(target, &errType)
}

func NewStringLengthError(reason string) error {
	return &StringLengthError{
		Reason: reason,
	}
}

func (e *StringLengthError) Error() string {
	return "StringLengthError error: " + e.Reason
}

func (e *StringLengthError) Is(target error) bool {
	var errType *StringLengthError
	return errors.As(target, &errType)
}

func NewTeamError(reason string) error {
	return &TeamError{
		Reason: reason,
	}
}

func (e *TeamError) Error() string {
	return "TeamError error: " + e.Reason
}

func (e *TeamError) Is(target error) bool {
	var errType *TeamError
	return errors.As(target, &errType)
}

func NewTypeError(reason string) error {
	return &TypeError{
		Reason: reason,
	}
}

func (e *TypeError) Error() string {
	return "TypeError error: " + e.Reason
}

func (e *TypeError) Is(target error) bool {
	var errType *TypeError
	return errors.As(target, &errType)
}

func NewUniqueError(reason string) error {
	return &UniqueError{
		Reason: reason,
	}
}

func (e *UniqueError) Error() string {
	return "UniqueError error: " + e.Reason
}

func (e *UniqueError) Is(target error) bool {
	var errType *UniqueError
	return errors.As(target, &errType)
}

// RaiseError raises an error based on the error type and reason.
func RaiseError(errorType, reason string) error {
	switch errorType {

	case "ApiError":
		return NewApiError(reason)

	case "ApiException":
		return NewApiException(reason)

	case "ApiVersionError":
		return NewApiVersionError(reason)

	case "ApplicationException":
		return NewApplicationException(reason)

	case "AuthenticationError":
		return NewAuthenticationError(reason)

	case "CollectionSizeError":
		return NewCollectionSizeError(reason)

	case "CommonError":
		return NewCommonError(reason)

	case "CompanyCreditStatusError":
		return NewCompanyCreditStatusError(reason)

	case "CompanyError":
		return NewCompanyError(reason)

	case "CrossSellError":
		return NewCrossSellError(reason)

	case "CustomFieldValueError":
		return NewCustomFieldValueError(reason)

	case "ExchangeSignupApiError":
		return NewExchangeSignupApiError(reason)

	case "FeatureError":
		return NewFeatureError(reason)

	case "InternalApiError":
		return NewInternalApiError(reason)

	case "InvalidEmailError":
		return NewInvalidEmailError(reason)

	case "InvalidUrlError":
		return NewInvalidUrlError(reason)

	case "InventoryClientApiError":
		return NewInventoryClientApiError(reason)

	case "LabelEntityAssociationError":
		return NewLabelEntityAssociationError(reason)

	case "McmError":
		return NewMcmError(reason)

	case "NetworkError":
		return NewNetworkError(reason)

	case "NotNullError":
		return NewNotNullError(reason)

	case "NullError":
		return NewNullError(reason)

	case "ParseError":
		return NewParseError(reason)

	case "PermissionError":
		return NewPermissionError(reason)

	case "PublisherQueryLanguageContextError":
		return NewPublisherQueryLanguageContextError(reason)

	case "PublisherQueryLanguageSyntaxError":
		return NewPublisherQueryLanguageSyntaxError(reason)

	case "QuotaError":
		return NewQuotaError(reason)

	case "RegExError":
		return NewRegExError(reason)

	case "RequiredCollectionError":
		return NewRequiredCollectionError(reason)

	case "RequiredError":
		return NewRequiredError(reason)

	case "RequiredNumberError":
		return NewRequiredNumberError(reason)

	case "ServerError":
		return NewServerError(reason)

	case "SiteError":
		return NewSiteError(reason)

	case "StatementError":
		return NewStatementError(reason)

	case "StringFormatError":
		return NewStringFormatError(reason)

	case "StringLengthError":
		return NewStringLengthError(reason)

	case "TeamError":
		return NewTeamError(reason)

	case "TypeError":
		return NewTypeError(reason)

	case "UniqueError":
		return NewUniqueError(reason)

	default:
		return nil
	}
}
